import createFetchClient from "openapi-fetch";
import type { paths } from "~/lib/api/schema"; // generated by openapi-typescript

export const $api = createFetchClient<paths>({
    baseUrl: "http://localhost:8084/",
});