export enum Routes {
    HOME = "/",
    DOWNLOADS = "/downloads",
    PANEL = "/panel",
    PANEL_ANALYTICS = "/panel/analytics",
    PANEL_VOUCHER = "/panel/voucher",
    LOGIN = "/login",
    INFORMATION = "/information",
    FETCH = "/fetch",
    PREVIEW = "/preview",
    LATEST = "/latest",
    CHECKOUT_CANCEL = "/checkout/cancel",
    CHECKOUT_SUCCESS = "/checkout/success",
    PRIVACY_POLICY = "/privacy-policy",
    TERMS = "/terms",
}