export enum Routes {
    HOME = "/",
    DOWNLOADS_BETTERBEDROCK = "/downloads/better-bedrock",
    DOWNLOADS_SIDE_PROJECTS = "/downloads/side-projects",
    DOWNLOADS_MAIN = "/downloads/main",
    PANEL = "/panel",
    PANEL_ANALYTICS = "/panel/analytics",
    PANEL_VOUCHER = "/panel/voucher",
    PANEL_PROJECTS = "/panel/projects",
    PROJECT = "/project",
    PROJECT_EDIT = "/project/edit",
    PROJECT_REVIEW = "/project/review",
    PROJECT_PREVIEW = "/project/preview",
    LOGIN = "/login",
    LINKVERTISE = "/linkvertise",
    INFORMATION = "/information",
    FETCH = "/verify",
    PROFILE = "/profile",
    LATEST = "/latest",
    CHECKOUT_CANCEL = "/checkout/cancel",
    CHECKOUT_SUCCESS = "/checkout/success",
    PRIVACY_POLICY = "/privacy-policy",
    TERMS = "/terms",
    CREATE = "/create",
    DISCORD = "/discord",
}